- hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"